### ISSUE TITLE
Practica 8 Matemáticas Discretas 

### ISSUE THREAD

**Issue by Proyect-A16** [SistemasTecTlaxiaco/actividad-8-practica-de-tablas-de-verdad-equipo-alan-ivan#1]
[Matematicas discretas Practica 8.pdf](https://github.com/user-attachments/files/17516592/Matematicas.discretas.Practica.8.pdf)

**Comment by Fidel20-01** [comment]
Evalucion de Practica 8
-Portada: 20/25
-Procedimiento:18/25
-Figuras, ilustraciones y figuras:22/25
-Resultado y conclusiones:25/25
Total de puntos:85/100
Calificacion: 17/20

**Comment by josealfredo79** [comment]
bien hecho y revisado...
